### ISSUE TITLE
As a system administrator, I want to distribute customer data across multiple storage nodes, so that a single point of failure doesn’t compromise all the data.

### ISSUE THREAD

**Issue by saitarunmandiga** [saitarunmandiga/Client_Connect#11]
**User Story 8: User Role and Permission Management**

**Acceptance Criteria:**
Managers can design and manage user roles and permissions within the system.
**Time Estimation**: 7-10 story points

**Comment by VSahithi1705** [comment]
@saitarunmandiga can you please give me access to make changes for the userstory
